version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "curedu"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1uvqcv470yfud"
s3_prefix = "curedu"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
